version: '3.7'

services:
  app:
    image: alfredojl/face_recognition
    ports:
      - 8080:8080

  back:
    image: franciscolopez29/face_recognition_back
    ports:
      - 3000:3000
    volumes:
      - ./volumen/reconocimientoDeVoz/audioDB:/app/reconocimientoDeVoz/audioDB